spring:
  cloud:
    config:
      name: ${spring.application.name}
      profile: local
      uri: http://localhost:9700

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.95.128:3306/sports?useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456

#spring.jackson.serialization.write-dates-as-timestamps=true
#spring.jackson.date-format=com.fasterxml.jackson.databind.util.StdDateFormat

python_web_url: http://localhost:8080
