eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka  # 设置与Eureka Server交互的地址查询服务和注册服务
  instance:
    instance-id: gateway-id
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.11.208:3306/sports?useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: testsmysql

  rabbitmq:
    host: 10.10.11.208
    port: 5672
    username: admin
    password: admin
    virtual-host: local

#spring.jackson.serialization.write-dates-as-timestamps=true
#spring.jackson.date-format=com.fasterxml.jackson.databind.util.StdDateFormat

python_web_url: http://localhost:8080
