server:
  port: 9999

spring:
  application:
    name: sports

eureka:
  client:
    service-url:
      defaultZone: http://eureka.gulang.work/eureka  # 设置与Eureka Server交互的地址查询服务和注册服务
  instance:
    instance-id: gateway-id
    prefer-ip-address: true

# mybatis
mybatis:
  typeAliasesPackage: com.spring.boot.sports.mapper
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

swagger:
  api:
    description: 权限管理服务
